var rainy = {
  "maxParticles": 125,
  "duration": 0,
  "lifeSpan": 2.65,
  "lifespanVariance": 0.45,
  "startSize": 10,
  "startSizeVariance": 4,
  "finishSize": 51,
  "finishSizeVariance": 56,
  "shape": "circle",
  "emitterType": 0,
  "location": {"x": 0, "y": 0},
  "locationVariance": {"x": 100, "y": 0},
  "speed": 476,
  "speedVariance": 126,
  "angle": 99,
  "angleVariance": 0,
  "gravity": {"x": -37, "y": 100},
  "radialAcceleration": 348,
  "radialAccelerationVariance": 0,
  "tangentialAcceleration": 10,
  "tangentialAccelerationVariance": 0,
  "minRadius": 0,
  "maxRadius": 329,
  "maxRadiusVariance": 0,
  "rotatePerSecond": 0,
  "rotatePerSecondVariance": 137,
  "compositeOperation": "lighter",
  "startColor": {"red": 0.2, "green": 0.73, "blue": 0.76, "alpha": 0.54},
  "finishColor": {"red": 0, "green": 1, "blue": 1, "alpha": 0}
};

var cloudy = {
  "maxParticles": 996,
  "duration": 0,
  "lifeSpan": 5,
  "lifespanVariance": 0,
  "startSize": 70,
  "startSizeVariance": 4,
  "finishSize": 66,
  "finishSizeVariance": 67,
  "shape": "circle",
  "emitterType": 1,
  "location": {"x": 0, "y": 0},
  "locationVariance": {"x": 0, "y": 100},
  "speed": 0,
  "speedVariance": 126,
  "angle": 299,
  "angleVariance": 0,
  "gravity": {"x": 108, "y": 21},
  "radialAcceleration": -500,
  "radialAccelerationVariance": 0,
  "tangentialAcceleration": 10,
  "tangentialAccelerationVariance": 0,
  "minRadius": 0,
  "maxRadius": 49,
  "maxRadiusVariance": 0,
  "rotatePerSecond": 0,
  "rotatePerSecondVariance": 52,
  "compositeOperation": "source-over",
  "startColor": {"red": 1, "green": 1, "blue": 1, "alpha": 0.74},
  "finishColor": {"red": 1, "green": 1, "blue": 1, "alpha": 0}
};

var foggy = {
  "maxParticles": 514,
  "duration": 0,
  "lifeSpan": 5,
  "lifespanVariance": 0,
  "startSize": 70,
  "startSizeVariance": 4,
  "finishSize": 66,
  "finishSizeVariance": 67,
  "shape": "circle",
  "emitterType": 0,
  "location": {"x": 0, "y": 0},
  "locationVariance": {"x": 100, "y": 0},
  "speed": 0,
  "speedVariance": 126,
  "angle": 299,
  "angleVariance": 0,
  "gravity": {"x": 108, "y": 21},
  "radialAcceleration": -500,
  "radialAccelerationVariance": 0,
  "tangentialAcceleration": 10,
  "tangentialAccelerationVariance": 0,
  "minRadius": 0,
  "maxRadius": 49,
  "maxRadiusVariance": 0,
  "rotatePerSecond": 0,
  "rotatePerSecondVariance": 52,
  "compositeOperation": "source-over",
  "startColor": {"red": 1, "green": 1, "blue": 1, "alpha": 0.01},
  "finishColor": {"red": 0.07, "green": 0.09, "blue": 0.08, "alpha": 0}
};

var snowy = {
  "maxParticles": 25,
  "duration": 0,
  "lifeSpan": 5,
  "lifespanVariance": 0.88,
  "startSize": 51,
  "startSizeVariance": 27,
  "finishSize": 35,
  "finishSizeVariance": 0,
  "shape": "circle",
  "emitterType": 0,
  "location": {"x": 0, "y": 0},
  "locationVariance": {"x": 100, "y": 100},
  "speed": 259,
  "speedVariance": 0,
  "angle": 90,
  "angleVariance": 0,
  "gravity": {"x": -500, "y": 500},
  "radialAcceleration": 500,
  "radialAccelerationVariance": 356,
  "tangentialAcceleration": -500,
  "tangentialAccelerationVariance": 0,
  "minRadius": 0,
  "maxRadius": 49,
  "maxRadiusVariance": 0,
  "rotatePerSecond": 0,
  "rotatePerSecondVariance": 52,
  "compositeOperation": "source-over",
  "startColor": {"red": 1, "green": 1, "blue": 1, "alpha": 1},
  "finishColor": {"red": 0.07, "green": 0.09, "blue": 0.08, "alpha": 0}
};

var sunny = {
  "maxParticles": 1416,
  "duration": 0,
  "lifeSpan": 5,
  "lifespanVariance": 0,
  "startSize": 70,
  "startSizeVariance": 0,
  "finishSize": 70,
  "finishSizeVariance": 0,
  "shape": "circle",
  "emitterType": 1,
  "location": {"x": 0, "y": 0},
  "locationVariance": {"x": 100, "y": 100},
  "speed": 259,
  "speedVariance": 0,
  "angle": 360,
  "angleVariance": 219,
  "gravity": {"x": -500, "y": 500},
  "radialAcceleration": 500,
  "radialAccelerationVariance": 356,
  "tangentialAcceleration": -500,
  "tangentialAccelerationVariance": 0,
  "minRadius": 0,
  "maxRadius": 49,
  "maxRadiusVariance": 0,
  "rotatePerSecond": 0,
  "rotatePerSecondVariance": 0,
  "compositeOperation": "source-over",
  "startColor": {"red": 1, "green": 0.93, "blue": 0.32, "alpha": 1},
  "finishColor": {"red": 0.07, "green": 0.09, "blue": 0.08, "alpha": 0}
};

var thunder = {
  "maxParticles": 1688,
  "duration": 0,
  "lifeSpan": 5,
  "lifespanVariance": 4.61,
  "startSize": 10,
  "startSizeVariance": 4,
  "finishSize": 0,
  "finishSizeVariance": 0,
  "shape": "circle",
  "emitterType": 0,
  "location": {"x": 0, "y": 0},
  "locationVariance": {"x": 100, "y": 0},
  "speed": 0,
  "speedVariance": 0,
  "angle": 203,
  "angleVariance": 0,
  "gravity": {"x": 8, "y": 500},
  "radialAcceleration": 149,
  "radialAccelerationVariance": 240,
  "tangentialAcceleration": 0,
  "tangentialAccelerationVariance": 0,
  "minRadius": 0,
  "maxRadius": 49,
  "maxRadiusVariance": 0,
  "rotatePerSecond": 0,
  "rotatePerSecondVariance": 0,
  "compositeOperation": "lighter",
  "startColor": {"red": 0.33, "green": 0.33, "blue": 0.89, "alpha": 0.2},
  "finishColor": {"red": 0.49, "green": 0.55, "blue": 1, "alpha": 1}
};

var windy = {
  "maxParticles": 116,
  "duration": 0,
  "lifeSpan": 5,
  "lifespanVariance": 4.61,
  "startSize": 70,
  "startSizeVariance": 0,
  "finishSize": 70,
  "finishSizeVariance": 13,
  "shape": "circle",
  "emitterType": 0,
  "location": {"x": 0, "y": 0},
  "locationVariance": {"x": 100, "y": 0},
  "speed": 500,
  "speedVariance": 0,
  "angle": 196,
  "angleVariance": 19,
  "gravity": {"x": -228, "y": 122},
  "radialAcceleration": 149,
  "radialAccelerationVariance": 0,
  "tangentialAcceleration": 500,
  "tangentialAccelerationVariance": 0,
  "minRadius": 0,
  "maxRadius": 49,
  "maxRadiusVariance": 0,
  "rotatePerSecond": 0,
  "rotatePerSecondVariance": 0,
  "compositeOperation": "lighter",
  "startColor": {"red": 1, "green": 1, "blue": 1, "alpha": 0},
  "finishColor": {"red": 1, "green": 1, "blue": 1, "alpha": 0.24}
};
